---

linux:
  hosts:
    aws-ubuntu:
      ansible_host: 54.211.182.133
      ansible user: ubuntu
  vars:
    ansible_ssh_private_key_file: /home/rachel_duffy/ceg2410-aws.pem

windows:
  hosts:

allsystems:
  children:
    linux:
    windows:
